### ISSUE TITLE
Why am I getting this error?

### ISSUE THREAD

**Issue by surya84** [mariuszfoltak/angular2-datatable#18]
![errir](https://cloud.githubusercontent.com/assets/6713590/16713901/834c3086-46d2-11e6-94a1-6aec91c0675f.PNG)

**Comment by dinagr** [comment]
I am having the same problems.
Did you find a solution?

**Comment by mariuszfoltak** [comment]
If you use systemjs, you should add configuration
```javascript
System.config({
  packages: [
    'angular2-datatable': { defaultExtension: 'js' },
    ...
  ]
});
```
You can check this file: https://github.com/mariuszfoltak/angular2-datatable/blob/master/examples/systemjs/systemjs.conf.js

**Comment by dinagr** [comment]
Thanks for your quick reply!
Now I get this error - 
zone.js:101 GET http://localhost:3000/angular2-datatable/datatable.js 404 (Not Found)

**Comment by mariuszfoltak** [comment]
You must add also configuration for mapping:
```javascript
System.config({
  map: {
    'angular2-datatable': 'node_modules/angular2-datatable',
  },
  packages: {
    'angular2-datatable': { defaultExtension: 'js' },
    ...
  }
});
```

**Comment by dinagr** [comment]
and for this?
zone.js:101 GET http://localhost:3000/lodash 404 (Not Found)

**Comment by mariuszfoltak** [comment]
```javascript
System.config({
  map: {
    'lodash': 'node_modules/lodash/lodash.js',
    ...
  },
  packages: {
    'lodash':                     { defaultExtension: 'js' },
    ...
  }
});
```

**Comment by dinagr** [comment]
Thanks a lot!!! 
It is working now
only the pagination is not working
I added this - 
```
<tfoot>
     <tr>
         <td colspan="4">
              <mfBootstrapPaginator [rowsOnPageSet]="[5,10,25]"></mfBootstrapPaginator>
         </td>
    </tr>
</tfoot>
```
between the </tbody> and the </table> tags
but the pagination is not showing
What else do I need to do?

**Comment by mariuszfoltak** [comment]
`mfBootstrapPaginator` is displayed only when data length is greather than min `rowsOnPage` value. Look at this example files: https://github.com/mariuszfoltak/angular2-datatable/tree/master/examples/systemjs/src

**Comment by kvbhaskar7** [comment]
Hi, 

I am new to angular and just setup my new angular2 application. I just setup angular2-datatable to my component and doesn't seems to be working. Not sure whats wrong here. Any help is really appreciated as i m really stuck and not able to proceed further.

When i comment out DataTableModule in app.module.ts, my app is working as expected with my features. 

**Error in my App loading:**
Error: (SystemJS) Unexpected value 'undefined' imported by the module 'AppModule'
	Error: Unexpected value 'undefined' imported by the module 'AppModule'
	    at eval (http://localhost:3276/node_modules/@angular/compiler/bundles/compiler.umd.js:14680:29) [<root>]
	    at Array.forEach (native) [<root>]
	    at CompileMetadataResolver._loadNgModuleMetadata (http://localhost:3276/node_modules/@angular/compiler/bundles/compiler.umd.js:14660:51) [<root>]
	    at CompileMetadataResolver.loadNgModuleMetadata (http://localhost:3276/node_modules/@angular/compiler/bundles/compiler.umd.js:14625:31) [<root>]
	    at RuntimeCompiler._loadModules (http://localhost:3276/node_modules/@angular/compiler/bundles/compiler.umd.js:17420:43) [<root>]
	    at RuntimeCompiler._compileModuleAndComponents (http://localhost:3276/node_modules/@angular/compiler/bundles/compiler.umd.js:17390:37) [<root>]
	    at RuntimeCompiler.compileModuleAsync (http://localhost:3276/node_modules/@angular/compiler/bundles/compiler.umd.js:17380:23) [<root>]
	    at PlatformRef_._bootstrapModuleWithZone (http://localhost:3276/node_modules/@angular/core/bundles/core.umd.js:6454:29) [<root>]
	    at PlatformRef_.bootstrapModule (http://localhost:3276/node_modules/@angular/core/bundles/core.umd.js:6436:25) [<root>]
	    at Object.eval (http://localhost:3276/app/main.js:7:10) [<root>]
	    at eval (http://localhost:3276/app/main.js:10:4) [<root>]
	    at eval (http://localhost:3276/app/main.js:11:3) [<root>]
	    at eval (<anonymous>) [<root>]
	Evaluating http://localhost:3276/app/main.js
	Error loading http://localhost:3276/app/main.js
	    at eval (http://localhost:3276/node_modules/@angular/compiler/bundles/compiler.umd.js:14680:29) [<root>]
	    at Array.forEach (native) [<root>]
	    at CompileMetadataResolver._loadNgModuleMetadata (http://localhost:3276/node_modules/@angular/compiler/bundles/compiler.umd.js:14660:51) [<root>]
	    at CompileMetadataResolver.loadNgModuleMetadata (http://localhost:3276/node_modules/@angular/compiler/bundles/compiler.umd.js:14625:31) [<root>]
	    at RuntimeCompiler._loadModules (http://localhost:3276/node_modules/@angular/compiler/bundles/compiler.umd.js:17420:43) [<root>]
	    at RuntimeCompiler._compileModuleAndComponents (http://localhost:3276/node_modules/@angular/compiler/bundles/compiler.umd.js:17390:37) [<root>]
	    at RuntimeCompiler.compileModuleAsync (http://localhost:3276/node_modules/@angular/compiler/bundles/compiler.umd.js:17380:23) [<root>]
	    at PlatformRef_._bootstrapModuleWithZone (http://localhost:3276/node_modules/@angular/core/bundles/core.umd.js:6454:29) [<root>]
	    at PlatformRef_.bootstrapModule (http://localhost:3276/node_modules/@angular/core/bundles/core.umd.js:6436:25) [<root>]
	    at Object.eval (http://localhost:3276/app/main.js:7:10) [<root>]
	    at eval (http://localhost:3276/app/main.js:10:4) [<root>]
	    at eval (http://localhost:3276/app/main.js:11:3) [<root>]
	    at eval (<anonymous>) [<root>]
	Evaluating http://localhost:3276/app/main.js
	Error loading http://localhost:3276/app/main.js

**app.module.ts**  
1. Added import { DataTableModule } from "angular2-datatable";
2. Imported @NgModule({
    imports: [   
        DataTableModule,  ]

**systemjs.config.js file**
/**
 * System configuration for Angular samples
 * Adjust as necessary for your application needs.
 */
(function (global) {
  System.config({
    paths: {
      // paths serve as alias
      'npm:': 'node_modules/'
    },
    // map tells the System loader where to look for things
    map: {
      // our app is within the app folder
      app: 'app',
      // angular bundles
      '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
      '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
      '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
      '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
      '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
      '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
      '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
      '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
      '@angular/upgrade': 'npm:@angular/upgrade/bundles/upgrade.umd.js',
      // other libraries
      'rxjs':                      'npm:rxjs',
      'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js',
      'angular2-datatable': 'node_modules/angular2-datatable/lib/datatable.js',
      'lodash': 'npm:lodash/lodash.js'
    },
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
      app: {
        main: './main.js',
        defaultExtension: 'js'
      },
      rxjs: {
        defaultExtension: 'js'
      },
      'angular2-datatable': { defaultExtension: 'js' },
    }
  });
})(this);

**package.json**
  "angular2-datatable": "^0.6.0",
    "lodash": "^4.17.2",

When i try to load my app, its failing with the error i mentioned above. Can someone please help !
