### ISSUE TITLE
Source Map refer to non existing ts files + _ is not defined when trying to use

### ISSUE THREAD

**Issue by msegers** [mariuszfoltak/angular2-datatable#4]
Hi I've installed angular2-datatable througn npm. then added the data tables directives array in my component, when loading this component I get the _ is not defined Error.

Also when SourceMap is enabled (webpack) they refer to the ts files which are not in the npm package.

Any tips on getting it to work?

```
EXCEPTION: ReferenceError: _ is not defined in [users in UserOverview@0:49]
?d41d:73 EXCEPTION: ReferenceError: _ is not defined in [users in UserOverview@0:49]BrowserDomAdapter.logError @ ?d41d:73BrowserDomAdapter.logGroup @ ?d41d:84ExceptionHandler.call @ ?d41d:49(anonymous function) @ ?d41d:258schedulerFn @ ?d41d:127SafeSubscriber.__tryOrUnsub @ VM12952:166SafeSubscriber.next @ VM12952:115Subscriber._next @ VM12952:74Subscriber.next @ VM12952:51Subject._finalNext @ VM12947:124Subject._next @ VM12947:116Subject.next @ VM12947:73EventEmitter.emit @ ?d41d:113NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ ?d41d:134NgZoneImpl.inner.inner.fork.onHandleError @ ?d41d:88ZoneDelegate.handleError @ zone.js?e3a6:368Zone.runGuarded @ zone.js?e3a6:274NgZoneImpl.runInner @ ?d41d:97NgZone.run @ ng_zone.ts?0378:204(anonymous function) @ ?d41d:399schedulerFn @ ?d41d:127SafeSubscriber.__tryOrUnsub @ VM12952:166SafeSubscriber.next @ VM12952:115Subscriber._next @ VM12952:74Subscriber.next @ VM12952:51Subject._finalNext @ VM12947:124Subject._next @ VM12947:116Subject.next @ VM12947:73EventEmitter.emit @ ?d41d:113NgZone._checkStable @ ?d41d:144NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.setMicrotask @ ?d41d:131NgZoneImpl.inner.inner.fork.onHasTask @ ?d41d:78ZoneDelegate.hasTask @ zone.js?e3a6:423ZoneDelegate._updateTaskCount @ zone.js?e3a6:440ZoneDelegate.invokeTask @ zone.js?e3a6:401Zone.runTask @ zone.js?e3a6:294drainMicroTaskQueue @ zone.js?e3a6:515ZoneTask.invoke @ zone.js?e3a6:467
?d41d:73 ORIGINAL EXCEPTION: ReferenceError: _ is not definedBrowserDomAdapter.logError @ ?d41d:73ExceptionHandler.call @ ?d41d:61(anonymous function) @ ?d41d:258schedulerFn @ ?d41d:127SafeSubscriber.__tryOrUnsub @ VM12952:166SafeSubscriber.next @ VM12952:115Subscriber._next @ VM12952:74Subscriber.next @ VM12952:51Subject._finalNext @ VM12947:124Subject._next @ VM12947:116Subject.next @ VM12947:73EventEmitter.emit @ ?d41d:113NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ ?d41d:134NgZoneImpl.inner.inner.fork.onHandleError @ ?d41d:88ZoneDelegate.handleError @ zone.js?e3a6:368Zone.runGuarded @ zone.js?e3a6:274NgZoneImpl.runInner @ ?d41d:97NgZone.run @ ng_zone.ts?0378:204(anonymous function) @ ?d41d:399schedulerFn @ ?d41d:127SafeSubscriber.__tryOrUnsub @ VM12952:166SafeSubscriber.next @ VM12952:115Subscriber._next @ VM12952:74Subscriber.next @ VM12952:51Subject._finalNext @ VM12947:124Subject._next @ VM12947:116Subject.next @ VM12947:73EventEmitter.emit @ ?d41d:113NgZone._checkStable @ ?d41d:144NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.setMicrotask @ ?d41d:131NgZoneImpl.inner.inner.fork.onHasTask @ ?d41d:78ZoneDelegate.hasTask @ zone.js?e3a6:423ZoneDelegate._updateTaskCount @ zone.js?e3a6:440ZoneDelegate.invokeTask @ zone.js?e3a6:401Zone.runTask @ zone.js?e3a6:294drainMicroTaskQueue @ zone.js?e3a6:515ZoneTask.invoke @ zone.js?e3a6:467
?d41d:73 ORIGINAL STACKTRACE:BrowserDomAdapter.logError @ ?d41d:73ExceptionHandler.call @ ?d41d:65(anonymous function) @ ?d41d:258schedulerFn @ ?d41d:127SafeSubscriber.__tryOrUnsub @ VM12952:166SafeSubscriber.next @ VM12952:115Subscriber._next @ VM12952:74Subscriber.next @ VM12952:51Subject._finalNext @ VM12947:124Subject._next @ VM12947:116Subject.next @ VM12947:73EventEmitter.emit @ ?d41d:113NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ ?d41d:134NgZoneImpl.inner.inner.fork.onHandleError @ ?d41d:88ZoneDelegate.handleError @ zone.js?e3a6:368Zone.runGuarded @ zone.js?e3a6:274NgZoneImpl.runInner @ ?d41d:97NgZone.run @ ng_zone.ts?0378:204(anonymous function) @ ?d41d:399schedulerFn @ ?d41d:127SafeSubscriber.__tryOrUnsub @ VM12952:166SafeSubscriber.next @ VM12952:115Subscriber._next @ VM12952:74Subscriber.next @ VM12952:51Subject._finalNext @ VM12947:124Subject._next @ VM12947:116Subject.next @ VM12947:73EventEmitter.emit @ ?d41d:113NgZone._checkStable @ ?d41d:144NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.setMicrotask @ ?d41d:131NgZoneImpl.inner.inner.fork.onHasTask @ ?d41d:78ZoneDelegate.hasTask @ zone.js?e3a6:423ZoneDelegate._updateTaskCount @ zone.js?e3a6:440ZoneDelegate.invokeTask @ zone.js?e3a6:401Zone.runTask @ zone.js?e3a6:294drainMicroTaskQueue @ zone.js?e3a6:515ZoneTask.invoke @ zone.js?e3a6:467
?d41d:73 ReferenceError: _ is not defined
    at DataTable.fillData (eval at <anonymous> (http://localhost:3000/main.bundle.js:57:2), <anonymous>:63:16)
    at DataTable.ngDoCheck (eval at <anonymous> (http://localhost:3000/main.bundle.js:57:2), <anonymous>:54:18)
    at AbstractChangeDetector.ChangeDetector_UserOverview_1.detectChangesInRecordsInternal (viewFactory_UserOverview:120:48)
    at AbstractChangeDetector.detectChangesInRecords (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:675:2), <anonymous>:104:18)
    at AbstractChangeDetector.runDetectChanges (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:675:2), <anonymous>:81:14)
    at AbstractChangeDetector._detectChangesContentChildren (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:675:2), <anonymous>:174:18)
    at AbstractChangeDetector.runDetectChanges (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:675:2), <anonymous>:82:14)
    at AbstractChangeDetector._detectChangesInViewChildren (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:675:2), <anonymous>:181:18)
    at AbstractChangeDetector.runDetectChanges (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:675:2), <anonymous>:85:14)
    at AbstractChangeDetector._detectChangesContentChildren (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:675:2), <anonymous>:174:18)
    at AbstractChangeDetector.runDetectChanges (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:675:2), <anonymous>:82:14)
    at AbstractChangeDetector._detectChangesInViewChildren (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:675:2), <anonymous>:181:18)
    at AbstractChangeDetector.runDetectChanges (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:675:2), <anonymous>:85:14)
    at AbstractChangeDetector._detectChangesContentChildren (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:675:2), <anonymous>:174:18)
    at AbstractChangeDetector.runDetectChanges (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:675:2), <anonymous>:82:14)
    at AbstractChangeDetector._detectChangesInViewChildren (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:675:2), <anonymous>:181:18)
    at AbstractChangeDetector.runDetectChanges (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:675:2), <anonymous>:85:14)
    at AbstractChangeDetector.detectChanges (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:675:2), <anonymous>:70:73)
    at ChangeDetectorRef_.detectChanges (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1093:2), <anonymous>:21:73)
    at eval (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1069:2), <anonymous>:387:84)
    at Array.forEach (native)
    at ApplicationRef_.tick (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1069:2), <anonymous>:387:38)
    at eval (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1069:2), <anonymous>:304:129)
    at ZoneDelegate.invoke (eval at <anonymous> (http://localhost:3000/polyfills.bundle.js:2444:2), <anonymous>:364:29)
    at Object.NgZoneImpl.inner.inner.fork.onInvoke (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1213:2), <anonymous>:44:41)
    at ZoneDelegate.invoke (eval at <anonymous> (http://localhost:3000/polyfills.bundle.js:2444:2), <anonymous>:363:35)
    at Zone.runGuarded (eval at <anonymous> (http://localhost:3000/polyfills.bundle.js:2444:2), <anonymous>:271:48)
    at NgZoneImpl.runInner (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1213:2), <anonymous>:75:71)
    at NgZone.run (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:456:2), <anonymous>:220:66)
    at Object.eval (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1069:2), <anonymous>:304:105)
    at SafeSubscriber.schedulerFn [as _next] (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:47:2), <anonymous>:122:52)
    at SafeSubscriber.__tryOrUnsub (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:241:2), <anonymous>:166:16)
    at SafeSubscriber.next (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:241:2), <anonymous>:115:22)
    at Subscriber._next (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:241:2), <anonymous>:74:26)
    at Subscriber.next (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:241:2), <anonymous>:51:18)
    at EventEmitter.Subject._finalNext (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:859:2), <anonymous>:124:30)
    at EventEmitter.Subject._next (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:859:2), <anonymous>:116:18)
    at EventEmitter.Subject.next (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:859:2), <anonymous>:73:14)
    at EventEmitter.emit (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:47:2), <anonymous>:111:76)
    at NgZone._checkStable (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:456:2), <anonymous>:140:44)
    at NgZoneImpl.NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.setMicrotask (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:456:2), <anonymous>:116:23)
    at Object.NgZoneImpl.inner.inner.fork.onHasTask (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1213:2), <anonymous>:56:35)
    at ZoneDelegate.hasTask (eval at <anonymous> (http://localhost:3000/polyfills.bundle.js:2444:2), <anonymous>:423:56)
    at ZoneDelegate._updateTaskCount (eval at <anonymous> (http://localhost:3000/polyfills.bundle.js:2444:2), <anonymous>:440:27)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:3000/polyfills.bundle.js:2444:2), <anonymous>:401:27)
    at Zone.runTask (eval at <anonymous> (http://localhost:3000/polyfills.bundle.js:2444:2), <anonymous>:294:48)
    at drainMicroTaskQueue (eval at <anonymous> (http://localhost:3000/polyfills.bundle.js:2444:2), <anonymous>:515:36)
    at HTMLDocument.ZoneTask.invoke (eval at <anonymous> (http://localhost:3000/polyfills.bundle.js:2444:2), <anonymous>:467:22)
```

**Comment by mariuszfoltak** [comment]
Hi,
You get the error, because I forgot about import lodash library in DataTable.ts. In new version (v0.2.4) it should work.
I don't know what to do with SourceMaps now, I never used webpack. I'll check it later, and release fix in next version.

**Comment by msegers** [comment]
Is that new version already there or is that an, in a few days thing?

Right now I just wrote 2 or 3 css classes to make it look like the material design spec

**Comment by mariuszfoltak** [comment]
Version v0.2.4 is already published in npm.
